services:
  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - ${DESIRED_NETWORK}
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  kibana:
    image: kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ${DESIRED_NETWORK}
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  fluentd:
    image: registry.authfy.com.br:5152/stg_y2_fluentd:1.10.18
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - ${DESIRED_NETWORK}
    ports:
      - target: 24224
        published: 24224
        protocol: tcp
        mode: host
      - target: 24224
        published: 24224
        protocol: udp
        mode: host
    depends_on:
      - elasticsearch

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

volumes:
  esdata:

networks:
  ${DESIRED_NETWORK}:
    external: true
    driver: overlay
