services:

  elasticsearch:
    image: elasticsearch:8.7.1
    restart: always
    expose:
      - 9200
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    networks:
      - logger_net

  kibana:
    image: kibana:8.7.1
    restart: always
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - logger_net

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - 24224:24224
      - 24224:24224/udp
    networks:
      - logger_net

volumes:
  esdata:

networks:
  logger_net: