services:
  elasticsearch:
    build: ./elasticsearch
    restart: always
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
      - MEM_LIMIT=2147483648
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - LICENSE=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - "esdata:/data"

  kibana:
    image: kibana:8.9.1
    restart: always
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - y2-centralized-logger 

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - 5140:5140
      - 5140:5140/udp
      - 24224:24224
      - 24224:24224/udp
    networks:
      - y2-centralized-logger 

networks:
  y2-centralized-logger: 
    name: "y2-centralized-logger"
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450  

volumes:
    esdata:

networks:
  y2cl_bridge:
    external: true
