services:

  elasticsearch:
    image: elasticsearch:8.7.1
    restart: always
    expose:
      - 9200
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    networks:
      - y2-centralized-logger 

  kibana:
    image: kibana:8.7.1
    restart: always
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - y2-centralized-logger 

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - 24224:24224
      - 24224:24224/udp
    networks:
      - y2-centralized-logger 

networks:
  y2-centralized-logger: 
    name: "y2-centralized-logger"
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450  

volumes:
  esdata: