services:

  elasticsearch:
    image: elasticsearch:8.7.1
    expose:
      - 9200
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
    volumes: 
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.7.1
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - 24224:24224
      - 24224:24224/udp

volumes:
  esdata: